### ISSUE TITLE
Child theme php error

### ISSUE THREAD

**Issue by phrizm** [bootscore/bootscore-child#17]
Hello Basti, thanks a lot for this great theme. 

I have a question regarding child theme, once installed main one and child, i got this strange error: 

Warning: filemtime(): stat failed for /home/mhd-01/*sitename*/htdocs/wp-content/themes/bootscore-child-main/css/main.css in /home/mhd-01/*sitename*/htdocs/wp-content/themes/bootscore-child-main/functions.php on line 11.

I have checked twice documentation available on project website, but got no luck to find an answer. 
Since im new in all that web stuff, i know basic theme structure, functions etc. but never worked with child themes. 

Thanks for your further answer, and keep going with this beautiful dev.

**Comment by crftwrk** [comment]
Hi phrizm,

thank you!

Are you on localhost? If so, it seems that this has something to do with your local server. Transfer your site to a public server should solve this, please share a link to your site to check.

But there may be something else. `bootscore-child-main/css/main.css` means that you use latest developed but not yet released version, downloaded here from GitHub. Make sure that you use latest developed parent theme too. Download and install both files and check the error again.

- https://github.com/bootscore/bootscore/archive/refs/heads/main.zip
- https://github.com/bootscore/bootscore-child/archive/refs/heads/main.zip

If the error still exists, transfer project to a different server.

Does this help?

**Comment by phrizm** [comment]
https://www.northwestalps.com/

I have installed your suggested versions. The error Still persists.

I do not touche anything there, just installed via wp dashboard. 

Thank you

**Comment by crftwrk** [comment]
phrizm.com seems to be fine? I don't see there any error?

northwestalps.com there is something wrong, but I cannot check from here. You can create a WP admin user and a ftp account and send them to store(at)bootscore.me. So I can check and fix it.

**Comment by phrizm** [comment]
Try to resize Window in phrizm. Here we go there appears.
